- name: set server, key, and apiserver
        continue-on-error: true
        shell: bash
        run: |
          sed -i -e 's|rs-ny.rustdesk.com|server.remotetechies.co.uk|' ./libs/hbb_common/src/config.rs
          sed -i -e 's|OeVuKk5nlHiXp+APNn0Y3pC1Iwpwn44JGqrQCsWqmBw=|sf9pHFUx0NSybnAAMLU+7xTYhJ9woGY850L2FwVi6cc=|' ./libs/hbb_common/src/config.rs
          sed -i -e 's|https://admin.rustdesk.com|https://server.remotetechies.co.uk|' ./src/common.rs
